### ISSUE TITLE
Exporting page names containing spaces returns incorrect page

### ISSUE THREAD

**Issue by anakaine** [sdearmond/arcgis-ddp-ddptoolbox#1]
An issue I have noticed is that your export script has a bug - Where a page is encountered that has a space in the name, the script will output the first page in the DDP table in its place. 

For example, here is a list of pages by name, and the resultant page that is exported in my project.
Acacia Ridge - Acacia Ridge
Adavale - Adavale
Albany Creek - Acacia Ridge
Allora - Allora
Anakie - Anakie
Brisbane City - Acacia Ridge

**Comment by sdearmond** [comment]
Hello anakaine. Thank you for submitting this issue. I have corrected the code. The trouble came when ArcMap would enclose complex page names in quotes before feeding the parameters to the python script. Python, not being able to find the right name, just exported page 1 over and over again. You can view the code that fixed the problem on lines 37 and 38 of ExportDDP.py.
